usePermissions: false
listen:
    respawn: true
worlds:
    normalWorld: world
    netherWorld: netherWorld
scale:
    normal: 8
    nether: 1
forceLoadRadius: 0
forcePeacefulNether: false
forceNetherNight: true
debug: false
